# Generated by Django 4.1.7 on 2023-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='article_bible_verse_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='article_bible_verse_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='article_paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='article_paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='article_paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Faith', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='header',
            field=models.CharField(default='Faith', max_length=50),
        ),
    ]
