# Generated by Django 4.1.7 on 2023-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_article_bible_verse_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='article_bible_verse_1_passage',
            field=models.CharField(blank='True', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='article_bible_verse_2_passage',
            field=models.CharField(blank='True', max_length=50),
        ),
    ]
