# Generated by Django 4.1.7 on 2023-03-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_article_bible_verse_1_passage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
