# Generated by Django 4.1.7 on 2023-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='article_paragraph_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='article_paragraph_5',
            field=models.TextField(blank=True),
        ),
    ]
