# Generated by Django 4.1.7 on 2023-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blog_article_paragraph_4_blog_article_paragraph_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default='..click to read!'),
        ),
    ]
